// This file is autogenerated by the JUCE BrowserIntegrationPluginClient class,
// by inspecting all the parameters in the AudioProcessorValueTreeState.
//
// It is updated whenever you run the app in debug mode with the macro
// BROWSER_INTEGRATION_WRITE_PARAMETER_CONFIG_IN_DEBUG=1.
//
// You shouldn't need to edit this manually - if you add a new parameter,
// running the app in debug mode should be enough to update this.

import { ParameterModel, PolygonModel } from './ParameterModel'
import { Vertex } from '../valueTree/InputStream'

export type ParametersType = {
	density: ParameterModel<number>
	stiffness: ParameterModel<number>
	pratio: ParameterModel<number>
	alpha: ParameterModel<number>
	beta: ParameterModel<number>
    xpos: ParameterModel<number>
    ypos: ParameterModel<number>
    vertices: PolygonModel<Array<Vertex>>
}

export const PARAMETER_IDS = ['density', 'stiffness', 'pratio', 'alpha', 'beta', 'xpos', 'ypos', 'vertices']
