name: build
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test workflow'  
  push:
    tags:
      - "v*"
env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  OPENSSL_ROOT_DIR: $(brew --prefix openssl@3)
  OPENSSL_INCLUDE_DIR: $(brew --prefix openssl@3)/include

jobs:
  macos-build:
    runs-on: macos-latest
    steps:
      - name: Install dependencies
        run: |
          brew install openssl@3
          brew link --force openssl@3
          ls "${{env.OPENSSL_ROOT_DIR}}"

      - name: Check out code
        uses: actions/checkout@v2
      - run: git submodule update --init --recursive

      - name: Setup torch
        run: |
          curl -L https://anaconda.org/pytorch/pytorch/1.13.1/download/osx-arm64/pytorch-1.13.1-py3.9_0.tar.bz2 | tar -xv

      - name: Build
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_PREFIX_PATH=${{ github.workspace }}/lib/python3.9/site-packages/torch -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
          make -j

  # AutomaticRelease:
  #   runs-on: macos-build
  #   needs: [arm64-build, x86_64-build]
  #   steps:
  #     - name: Download build binaries
  #       uses: actions/download-artifact@v2
  #       with:
  #         name: torchplugins
  #     - name: Automated Release
  #       uses: "marvinpinto/action-automatic-releases@latest"
  #       with:
  #         repo_token: "${{ secrets.GITHUB_TOKEN }}"
  #         prerelease: false
  #         files: |
  #           torchplugins_macOS_x86_64.tar.gz
  #           torchplugins_macOS_arm64.tar.gz